networks:
  citrixhoneypot_local:

services:

# CitrixHoneypot service
  citrixhoneypot:
    build: .
    container_name: citrixhoneypot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - citrixhoneypot_local
    ports:
     - "443:443"
    image: "dtagdevsec/citrixhoneypot:24.04"
    read_only: true
    volumes:
     - $HOME/tpotce/data/citrixhoneypot/log:/opt/citrixhoneypot/logs
