networks:
  mailoney_local:

services:

# Mailoney service
  mailoney:
    build: .
    container_name: mailoney
    stdin_open: true
    tty: true
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - mailoney_local
    ports:
     - "25:25"
     - "587:25"
    image: "dtagdevsec/mailoney:24.04"
    read_only: true
    volumes:
     - $HOME/tpotce/data/mailoney/log:/opt/mailoney/logs
