networks:
  honeypots_local:

services:

# Honeypots service
  honeypots:
    build: .
    container_name: honeypots
    stdin_open: true
    tty: true
    restart: always
    tmpfs:
     - /tmp:uid=2000,gid=2000
#    cpu_count: 1
#    cpus: 0.75
    networks:
     - honeypots_local
    ports:
     - "21:21"
     - "22:22"
     - "23:23"
     - "25:25"
     - "53:53/udp"
     - "67:67/udp"
     - "80:80"
     - "110:110"
     - "123:123"
     - "143:143"
     - "161:161"
     - "389:389"
     - "443:443"
     - "445:445"
     - "631:631"
     - "1080:1080"
     - "1433:1433"
     - "1521:1521"
     - "3306:3306"
     - "3389:3389"
     - "5060:5060/tcp"
     - "5060:5060/udp"
     - "5432:5432"
     - "5900:5900"
     - "6379:6379"
     - "6667:6667"
     - "8080:8080"
     - "9100:9100"
     - "9200:9200"
     - "11211:11211"
    image: "dtagdevsec/honeypots:24.04"
    read_only: true
    volumes:
     - $HOME/tpotce/data/honeypots/log:/var/log/honeypots
