networks:
  redishoneypot_local:

services:

# redishoneypot service
  redishoneypot:
    build: .
    container_name: redishoneypot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - redishoneypot_local
    ports:
     - "6379:6379"    
    image: "dtagdevsec/redishoneypot:24.04"
    read_only: true
    volumes:
     - $HOME/tpotce/data/redishoneypot/log:/var/log/redishoneypot
