networks:
  hellpot_local:

services:

# hellpot service
  hellpot:
    build: .
    container_name: hellpot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - hellpot_local
    ports:
     - "80:8080"
    image: "dtagdevsec/hellpot:24.04"
    read_only: true
    volumes:
     - $HOME/tpotce/data/hellpot/log:/var/log/hellpot
