services:

# Fatt service
  fatt:
    build: .
    container_name: fatt
    stdin_open: true
    tty: true
    restart: always
#    cpu_count: 1
#    cpus: 0.75
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    image: "ghcr.io/telekom-security/fatt:24.04.1"
    volumes:
     - $HOME/tpotce/data/fatt/log:/opt/fatt/log
